version: "3"

networks:
  bittery-net:

services:

  lnd_bitcoin:
    image: lightninglabs/lnd:${LND_HOSTED_VERSION}
    container_name: lnd_bitcoin
    restart: unless-stopped
    volumes:
      - ./volumes/lnd:/root/.lnd
    networks:
      - bittery-net
    expose:
      - 8080
      - 10009
    ports:
      - 9735:9735

  nginx:
    restart: unless-stopped
    image: nginx:1.19.4
    container_name: nginx
    volumes:
      - ./volumes/nginx/conf:/etc/nginx/conf.d:rw
      - ./volumes/nginx/vhost:/etc/nginx/vhost.d
      - ./volumes/nginx/html:/usr/share/nginx/html
      - ./volumes/nginx/certs:/etc/nginx/certs:ro
      - ./volumes/lnd/:/etc/nginx/lnd
    networks:
      - bittery-net
    ports:
      - 443:443
      - 10009:10009
