export enum EncryptedLnArtefactType {
    ADMIN_MACAROON_HEX = 'ADMIN_MACAROON_HEX',
    CUSTOM_MACAROON_HEX = 'ADMIN_MACAROON_HEX',
    LN_SEED_MNEMONIC = 'LN_SEED_MNEMONIC',
    LN_PASSWORD = 'LN_SEED',
}
