export enum DigitalOceanLndDeploymentStageType {
    DROPLET_CREATION = '1_DROPLET_CREATION',
    DROPLET_IP_OBTAIN = '2_DROPLET_IP_OBTAIN',
    SSH_CONNECTION = '3_SSH_CONNECTION',
    PUT_LND_FILES = '4_PUT_LND_FILES',
    START_LND = '5_START_LND',
    DOWNLOAD_TLS_CERT = '6_DOWNLOAD_TLS_CERT',
    AFTER_INSTALLATION = '7_AFTER_INSTALLATION',
}
