version: '2'

networks:
  bittery-net:
    external:
      name: docker-compose_bittery-net

services:

  bittery-backend:
    image: bittery-backend
    container_name: bittery-backend
    environment:
      - DB_USER=master
      - DB_HOST=bittery-postgres
      - DB_DATABASE=bitteryio
      - DB_PASSWORD=ofpuppets
      - DB_PORT=5432
      - ENCRYPTION_PASSWORD_SALT_ROUNDS=8
      - OAUTH2_TOKEN_CLIENT_SECRET=u8eFLaz_oXsB
      - SESSION_EXPIRES_IN_HOURS=1
      - AUTH_EXCLUDED_URLS=["/user/refreshToken","/user/register","/user/register/confirm","/user/login","/public", "/user/password/reset", "/user/password/reset/confirm"]
      - RTL_URL=/rtl
      - BTCPAY_URL=http://btcpayserver:49392
      - CLIENT_URL_ADDRESS=http://bittery.io:8080
      - IS_DEVELOPMENT_ENV=true
      - DEVELOPMENT_HOSTNAME=emergencja
      - MAILGUN_API_KEY=9f5866cc80a8850ea8dde149cb869c94-1b6eb03d-9e643989
      - BTCPAY_ADMIN_LOGIN=peerzet3@gmail.com
      - BTCPAY_ADMIN_PASSWORD=asdfasdf
      - PASSWORD_RESET_LINK_VALIDITY_HOURS=4
      - PASSWORD_RESET_EMAIL_HOURS_MEASURE_PERIOD_HOURS=24
      - PASSWORD_RESET_EMAIL_MEASURE_PERIOD_LIMIT=2
      - REGISTRATION_ENABLED=true
      - LOGIN_ENABLED=true
      - CREATE_INVOICE_ENABLED=true
      - INVOKE_SERVER_PORT=3002
    volumes:
      - /home/peer/Programowanie/bittery/bittery-infrastructure:/bittery-infrastructure
      - ./volumes/logs:/logs
    networks:
      - bittery-net
    ports:
      - 3001:3001
