version: '2'

networks:
  bittery-net-ext:
    external:
      name: docker-compose_bittery-net

services:

  bittery-postgres:
    image: postgres:15.3-alpine
    container_name: bittery-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: bittery
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - bittery-net-ext
    ports:
      - 5436:5432
