export enum UserRegistrationErrorType {
    USERNAME_ALREADY_TAKEN,
    EMAIL_ALREADY_TAKEN,
    EMAIL_INCORRECT,
    PASSWORDS_NOT_MATCH,
    PASSWORD_INCORRECT,
    USERNAME_INCORRECT,
    CONFIRMATION_EMAIL_SENT_FAILED,
    NO_CONFIRMATION_ENTRY_EXIST,
    CAPTCHA_VALIDATION_FAILED,
    REGISTRATION_TEMPORARY_DISABLED,
}
