export enum DisableSubscriptionStageErrorType {
    BACKUP_LND_ERROR = '1_BACKUP_LND_ERROR',
    DELETE_DROPLET_ERROR = '2_DELETE_DROPLET_ERROR',
    DATABASE_UPDATE_ERROR = '3_DATABASE_UPDATE_ERROR',
}
