export enum DisableSubscriptionStageErrorType {
    STATIC_CHANNEL_BACKUP_ERROR = '1_BACKUP_LND_ERROR',
    BACKUP_LND_ERROR = '2_BACKUP_LND_ERROR',
    DELETE_DROPLET_ERROR = '3_DELETE_DROPLET_ERROR',
    DATABASE_UPDATE_ERROR = '4_DATABASE_UPDATE_ERROR',
}
