export enum NotificationReasonEnum {
    REGISTRATION = 'REGISTRATION',
    PASSWORD_RESET = 'PASSWORD_RESET',
    SUBSCRIPTION_ENDS_IN_3_DAYS = 'SUBSCRIPTION_ENDS_IN_3_DAYS',
    SUBSCRIPTION_ENDS_IN_7_DAYS = 'SUBSCRIPTION_ENDS_IN_7_DAYS',
    SUBSCRIPTION_ENDED = 'SUBSCRIPTION_ENDED',
}
